/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type ApplicationOptionKind = "campus" | "course" | "faculty" | "support_provider";

export type ApplicationStatus = "awarded" | "draft" | "rejected" | "shortlisted" | "submitted" | "under_review";

export type DocumentType = "essay" | "id_document" | "transcript";

export type EmailNotificationStatus = "failed" | "queued" | "sent";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserRole = "admin" | "student";

export interface ApplicationAdminNotes {
  application_id: string;
  content: string;
  created_at: Generated<Timestamp>;
  created_by_user_id: string;
  id: string;
}

export interface ApplicationAttachments {
  application_id: string;
  id: string;
  mime_type: string;
  original_filename: string;
  s3_key: string;
  size_bytes: number;
  slot_key: string;
  uploaded_at: Generated<Timestamp>;
}

export interface ApplicationDocuments {
  application_id: string;
  doc_type: DocumentType;
  id: string;
  mime_type: string;
  original_filename: string;
  s3_key: string;
  size_bytes: number;
  uploaded_at: Generated<Timestamp>;
}

export interface ApplicationFormData {
  application_id: string;
  created_at: Generated<Timestamp>;
  payload: Generated<Json>;
  updated_at: Generated<Timestamp>;
}

export interface ApplicationOptionItems {
  created_at: Generated<Timestamp>;
  id: string;
  is_active: Generated<boolean>;
  kind: ApplicationOptionKind;
  label: string;
  parent_id: string | null;
  sort_order: number;
  updated_at: Generated<Timestamp>;
}

export interface Applications {
  admin_notes: string | null;
  created_at: Generated<Timestamp>;
  id: string;
  locked_at: Timestamp | null;
  reopened_at: Timestamp | null;
  scholarship_id: string;
  status: ApplicationStatus;
  student_user_id: string;
  submitted_at: Timestamp | null;
  updated_at: Generated<Timestamp>;
}

export interface ApplicationStatusHistory {
  application_id: string;
  changed_at: Generated<Timestamp>;
  changed_by_user_id: string;
  from_status: ApplicationStatus | null;
  id: string;
  reason: string | null;
  to_status: ApplicationStatus;
}

export interface EmailNotifications {
  application_id: string;
  created_at: Generated<Timestamp>;
  error: string | null;
  id: string;
  provider_message_id: string | null;
  recipient_email: string;
  sent_at: Timestamp | null;
  status: EmailNotificationStatus;
  template_key: string;
  updated_at: Generated<Timestamp>;
}

export interface PasswordResetTokens {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  token_hash: string;
  used_at: Timestamp | null;
  user_id: string;
}

export interface SchemaMigrations {
  applied_at: Generated<Timestamp>;
  filename: string;
  id: Generated<number>;
}

export interface Scholarships {
  amount: Numeric;
  created_at: Generated<Timestamp>;
  created_by: string;
  currency: string;
  deadline_at: Timestamp;
  description: string;
  education_level: string | null;
  eligibility_text: string;
  id: string;
  image_url: string | null;
  is_published: Generated<boolean>;
  slug: string;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface StudentProfiles {
  created_at: Generated<Timestamp>;
  date_of_birth: string | null;
  full_name: string;
  gpa: Numeric | null;
  graduation_year: number | null;
  institution: string;
  phone: string;
  program: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface StudyPrograms {
  created_at: Generated<Timestamp>;
  id: string;
  name: string;
  sort_order: Generated<number>;
  updated_at: Generated<Timestamp>;
}

export interface Users {
  created_at: Generated<Timestamp>;
  email: string;
  id: string;
  password_hash: string;
  role: UserRole;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  application_admin_notes: ApplicationAdminNotes;
  application_attachments: ApplicationAttachments;
  application_documents: ApplicationDocuments;
  application_form_data: ApplicationFormData;
  application_option_items: ApplicationOptionItems;
  application_status_history: ApplicationStatusHistory;
  applications: Applications;
  email_notifications: EmailNotifications;
  password_reset_tokens: PasswordResetTokens;
  schema_migrations: SchemaMigrations;
  scholarships: Scholarships;
  student_profiles: StudentProfiles;
  study_programs: StudyPrograms;
  users: Users;
}
